#!/bin/sh
TWS=".."
MYOBJS="."
rm -f _TREE _CODE
echo "YAHOO ! The Tiny Compiler-Interpreter:"
echo ""
if [ ${#} -eq 0 ]
then
  echo "Usage: ${0} <input file>"
  echo "  or you will be prompted for the file."
  echo
  echo -n "Input file: "
  read INPUT
else
  INPUT=${1}
fi  
parser/parse < ${INPUT} || exit 1
echo "Done parsing."
echo "Enter Constrainer ..."
$MYOBJS/Constrain -trace _CONS
#echo "Enter CodeGenerator ..."
#$MYOBJS/CodeGen -trace _CGEN
#echo "Starting Interpreter ..."
#$TWS/bin/interpret ${2}
